content:
  - name: projects
    label: Projects
    path: src/data/projects
    type: collection
    filename: '{fields.slug}.md'
    view:
      fields: [heroimage, title, pubdatetime, featured]
      sort: [ pubdatetime, featured ]
      search: [ title ]
      default:
        search: ''
        sort: featured
        order: desc
    fields:
      - name: pubdatetime
        label: Publication Date
        type: date
        options:
          time: true
          format: yyyy-MM-dd'T'HH:mm:ss'Z'
      - name: featured
        label: Is Featured
        type: boolean
      - name: title
        label: Title
        type: string
      - name: slug
        label: Slug
        type: string
      - name: status
        label: Status
        type: select
        options:
          values: [Active, Hiatus, Defunct]
      - name: description
        label: Description
        type: string
      - name: tags
        label: Tags
        type: select
        options:
          multiple: true
          values: [Technology, Sports, Music, Design]
      - name: body
        label: Body
        type: rich-text
      - name: heroimage
        label: Hero Image
        type: image
  - name: experience
    label: Experience
    path: src/data/experience
    type: collection
    filename: '{fields.company}.md'
    view:
      fields: [icon, company, role, startdate]
      search: [ title ]
      default:
        search: ''
        sort: pubDate
        order: desc
    fields:
      - name: startdate
        label: Start Date
        type: date
        options:
          time: true
          format: yyyy-MM-dd
      - name: enddate
        label: End Date
        type: date
        options:
          time: true
          format: yyyy-MM-dd
      - name: icon
        label: Icon
        type: image
      - name: company
        label: Company
        type: string
      - name: location
        label: Location
        type: string
      - name: country
        label: Country
        type: select
        options:
          values: [ AU, PH ]
      - name: roles
        label: Roles
        type: select
        options:
          multiple: true
          values: [Automation Test Engineer, Automation Test Consultant, SDET, Systems Architect, Software Developer, Senior Web Developer]
      - name: current
        label: Is Current
        type: boolean
      - name: description
        label: Description
        type: text
      - name: responsibilities
        label: Responsibilities
        type: rich-text
      - name: techUsed
        label: Technologies Used
        type: select
        options:
          multiple: true
          values: [.NET, SpecFlow, Reqnroll, Selenium, Selenoid, MS Test, NUnit, Postman, Visual Studio, VS Code, JavaScript, TypeScript, Taiko, Gauge, Jira, Confluence, Azure Devops, Rally Dev, Angular JS, Amadeus, Travelport Sabre, ASP .NET MVC, Invision, Silverlight, WPF, VB .NET, VB6, InstallShield X]
  - name: HomepageSettings
    label: Homepage Settings
    path: src/data/homepage.json
    type: file
    fields:
      - name: role
        label: Role
        type: string
      - name: location
        label: Location
        type: string
      - name: linkedIn
        label: Linkedin
        type: string
      - name: github
        label: Github
        type: string
      - name: email
        label: Email
        type: string
      - name: aboutMe
        label: About Me
        type: html
media:
  - name: files
    label: Files
    input: public/images
    output: public/images
    categories: [ jpg, webp, png ]