content:
  - name: projects
    label: Projects
    path: src/data/projects
    type: collection
    filename: '{fields.slug}.md'
    view:
      fields: [heroImage, title, pubDatetime, featured]
      sort: [ pubDatetime, featured ]
      search: [ title ]
    fields:
      - name: pubDatetime
        label: Publication Date
        type: date
        options:
          time: true
          format: yyyy-MM-dd'T'HH:mm:ss'Z'
      - name: featured
        label: Is Featured
        type: boolean
      - name: title
        label: Title
        type: string
      - name: slug
        label: Slug
        type: string
      - name: status
        label: Status
        type: select
        options:
          values: 
            - value: active
              label: Active
            - value: hiatus
              label: Hiatus
            - value: defunct
              label: Defunct
          
      - name: description
        label: Description
        type: string
      - name: tag
        label: Tag
        type: select
        options:
          mutilple: true
          values:
            - value: tech
              label: Technology
            - value: sports
              label: Sports
            - value: music
              label: Music
      - name: body
        label: Body
        type: rich-text
      - name: heroImage
        label: Hero Image
        type: image
  - name: experience
    label: Experience
    path: src/data/experience
    type: collection
    filename: '{fields.company}.md'
    view:
      fields: [icon, company, role, pubDate]
    fields:
      - name: startDate
        label: Start Date
        type: date
        options:
          time: true
          format: yyyy-MM
      - name: endtime
        label: End Date
        type: date
        options:
          time: true
          format: yyyy-MM
      - name: icon
        label: Icon
        type: image
      - name: company
        label: Company
        type: string
      - name: location
        label: Location
        type: string
      - name: country
        label: Country
        type: select
        options:
          values: [ AU, PH ]
      - name: role
        label: Role
        type: select
        options:
          multiple: true
          values:
            - value: automation-test-engineer
              label: Automation Test Engineer
            - value: automation-test-consultant
              label: Automation Test Consultant
            - value: sdet
              label: SDET
            - value: systems-architect
              label: Systems Architect
            - value: systems-analyst
              label: Systems Analyst
            - value: software-developer
              label: Software-Developer
            - value: senior-web-developer
              label: Senior Web Developer
      - name: status
        label: Status
        type: select
        options:
          values: [ current, past ]
      - name: description
        label: Description
        type: text
      - name: responsibilities
        label: Responsibilities
        type: rich-text
      - name: techUsed
        label: Technologies Used
        type: select
        options:
          multiple: true
          values:
            - value: dotnet
              label: .NET
            - value: specflow
              label: SpecFlow
            - value: reqnroll
              label: Reqnroll
            - value: selenium
              label: Selenium
            - value: selenoid
              label: Selenoid
            - value: mstest
              label: MS Test
            - value: nunit
              label: NUnit
            - value: postman
              label: Postman
            - value: visual-studio
              label: Visual Studio
            - value: visual-studio-code
              label: VS Code
            - value: javascript
              label: JavaScript
            - value: typescript
              label: TypeScript
            - value: taiko
              label: Taiko
            - value: gauge
              label: gauge
            - value: jira
              label: Jira
            - value: confluence
              label: Confluence
            - value: azure-devops
              label: Azure Devops
            - value: rally-dev
              label: Rally Dev
            - value: angular
              label: Angular JS
            - value: amadeus
              label: Amadeus
            - value: travelport
              label: Travelport
            - value: sabre
              label: Sabre
            - value: asp-dotnet-mvc
              label: ASP .NET MVC
            - value: invision
              label: Invision
            - value: silverlight
              label: Silverlight
            - value: wpf
              label: WPF
            - value: vb-dotnet
              label: VB .NET
            - value: vb6
              label: VB6
            - value: installshield-x
              label: InstallShield X
  - name: HomepageSettings
    label: Homepage Settings
    path: src/data/homepage.json
    type: file
    fields:
      - name: role
        label: Role
        type: string
      - name: location
        label: Location
        type: string
      - name: linkedIn
        label: Linkedin
        type: string
      - name: github
        label: Github
        type: string
      - name: email
        label: Email
        type: string
      - name: aboutMe
        label: About Me
        type: html
media:
  - name: files
    label: Files
    input: public/images
    output: public/images
    categories: [ jpg, webp, png ]